"""Baseline schema.

The state the database was already in when Alembic was adopted, generated from
the models so it matches exactly.

**An existing database never runs this.** `app.db.init_db` detects a database
that predates Alembic, brings it up to this shape with the old hand-rolled
ladder one final time, then stamps this revision without executing it. Only a
brand-new database actually creates these tables here.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mp3_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('mp3_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mp3_collections_kind'), ['kind'], unique=False)

    op.create_table('mp3_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    with op.batch_alter_table('mp3_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mp3_files_kind'), ['kind'], unique=False)

    op.create_table('collection_mp3s',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('mp3_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['mp3_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mp3_id'], ['mp3_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'mp3_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('use_https', sa.Boolean(), nullable=False),
    sa.Column('last_applied_mp3_id', sa.Integer(), nullable=True),
    sa.Column('last_applied_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_applied_mp3_id'], ['mp3_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('mp3_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['mp3_collections.id'], ),
    sa.ForeignKeyConstraint(['mp3_id'], ['mp3_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_schedule_name')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_kind'), ['kind'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('mp3_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['mp3_id'], ['mp3_files.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('schedule_devices',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_devices')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))

    op.drop_table('audit_log')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_kind'))

    op.drop_table('schedules')
    op.drop_table('devices')
    op.drop_table('collection_mp3s')
    with op.batch_alter_table('mp3_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mp3_files_kind'))

    op.drop_table('mp3_files')
    with op.batch_alter_table('mp3_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mp3_collections_kind'))

    op.drop_table('mp3_collections')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
