"""Per-device TLS verification.

Adds `devices.verify_tls`, defaulting to off so every existing device keeps
behaving exactly as it did. TLS verification was previously disabled
unconditionally in code, with no way for anyone who had put a real certificate
on their door station to turn it back on.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002_verify_tls'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_tls', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('verify_tls')

    # ### end Alembic commands ###
